name: Push On Develop

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  update-upm-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set Git identity
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Rename Samples folder if needed
      run: |
        if [[ -d "Samples" ]]; then
          git mv Samples Samples~
          rm -f Samples.meta
          git commit -m "Samples folder renamed without ~"
          git push origin HEAD
          echo "Samples folder renamed without ~"
        else
          echo "Samples folder already in correct format"
        fi

    - name: Push Branch and Tags
      run: |
        git subtree split --prefix=Packages/com.ingsorre97.render-hell -b develop-upm-split
        git checkout upm
        git merge --squash develop-upm-split
        git commit -m "Updated UPM package"
        git push origin HEAD
        git branch -D develop-upm-split
        
          